### ISSUE TITLE
Error black screen after custom Antenna input - iOS 3.8.5

### ISSUE THREAD

**Issue by akavics1** [helium/hotspot-app#1176] opened 2021-12-22 14:44 UTC
**Describe the bug**
I use custom 6.5dbi antenna. I wanted to set up the custom antenna value and after the 6.5 has been given and try to tap into the height or just press "done" text the whole menu is disappeared and I have only the X button on the top right to exit.

The same issue when I want to type the height data first then tap into the antenna value.

**To Reproduce**

1. Go to 'update hotpsot
2. type in any number (TX/RX gain) place 
3. then tap into the height input field.'
4. Black screen coming out

**Expected behavior**
Should come up the other input field then I need to able scroll down to finish the setup

**Screenshots**
https://user-images.githubusercontent.com/96535231/147109794-c6578338-0bdf-490d-9661-d161b449211a.mp4

**Smartphone (please complete the following information):**
- Device: [iPhone 12]
- OS: [IOS 15.1]
- App Version [3.8.5]

**Additional context**
Tried to re-install the application. I logged out, then deleted app, then re-downloaded then logged in word the 12 words then the same issue happened.

**Comment by cokes518** [comment] 2021-12-22 17:38
Thanks for reporting. I can't see to view the video, do you mind reuploading it? 
@tyler-whitman for you when you get back from the break.

**Comment by cokes518** [comment] 2022-01-10 19:29
duplicate of #1083 , will be fixed by #1193

**Closed** 2022-01-10 19:29 UTC
Labels: bug, duplicate
