### ISSUE TITLE
Buttons on Hotspot screen doesn't work

### ISSUE THREAD

**Issue by piodabro** [helium/hotspot-app#1057] opened 2021-11-08 18:35 UTC
When trying to add new hotspot i'm clicking on blue "Hotspots" drop-down button and then on "+ Add hotspot".
Application does nothing just closes the drop-down. The same for other buttons in this page for both drop-downs - Hotspots and Validators
This happens on newest app from Google Play store.

Tested on two different phones, the behavior is the same.
Phones: POCO X3 and Xiaomi Mi A1

**To Reproduce**

1. Download app from Google Play Store
2. Create new account.
3. Accept location permission.
4. Go to hotspots screen and tap blue "Hotspots" drop-down button.
5. Click on White "+ Add hotspot" button. (or any other button)
6. Nothing happens, only dropdown closes.

**Expected behavior**
Should open "Add hotspot" screen.

**Screenshots**

**Smartphone (please complete the following information):**

- Device: POCO X3, Xiaomi Mi A1
- OS: POCO X3: Android 11 with MIUI 12.5.2, Mi A1: Android 9 (from Android One family)
- App Version v3.8.0

**Comment by abhay** [comment] 2021-11-08 18:38
closing as dupe of #1056

**Closed by abhay** 2021-11-08 18:38 UTC
Labels: bug
