### ISSUE TITLE
Hotspots Are Mining But Not Adding To Helium Wallet

### ISSUE THREAD

**Issue by fostdev1** [helium/hotspot-app#1276] opened 2022-03-30 00:39 UTC
The last 2 days my miners have been mining HNT as shown in the explorer, however my wallet in the iOS app hasn’t changed value in 2 days, it’s stayed at 13.6 HNT. Is this just an app bug?

**Comment by csestonia** [comment] 2022-03-30 13:20
Have exact same issue.
Last 2 days my wallet haven’t change in value.
Im earning and I see it in rewards, but the value stays the same!!!

**Comment by fostdev1** [comment] 2022-03-30 14:09
> Have exact same issue.
> Last 2 days my wallet haven’t change in value.
> Im earning and I see it in rewards, but the value stays the same!!!

I might've figured it out. Make sure you have your 12 words copied down then try logging out and logging back in. Fixed it for me

**Comment by csestonia** [comment] 2022-03-30 16:34
> 

Yep,
Worked for me also!
Strange bug!
Can you imagine people who do like A LOT PER DAY, see no value changing?!

**Comment by fostdev1** [comment] 2022-03-30 16:40
Yeah wtf. I almost freaked on just my 0.6HNT a day. lol

**Comment by csestonia** [comment] 2022-03-30 16:56
> Yeah wtf. I almost freaked on just my 0.6HNT a day. lol

Wow dude, beautiful earnings.
Wanna give me some tips how to get it until this day value?
My discord Lnk#7919

**Comment by fostdev1** [comment] 2022-03-30 17:05
> > Yeah wtf. I almost freaked on just my 0.6HNT a day. lol
> 
> Wow dude, beautiful earnings. Wanna give me some tips how to get it until this day value? My discord Lnk#7919

It's not that impressive, I have 3 hotspots lol so I usually get 0.6-0.9 a day, sometimes less. Each hotspot gets anywhere from 0.1-0.4. The only tip I have is to just get your antenna outside, for each of my locations I have an antenna on the roof and run a quality cable inside. Then choose your dbi for your antenna based on the hotspots around you. If you're surrounded by lots of other hotspot get like a 3dbi, if you need to reach out to further away hotspots get like 8dbi-12dbi. Currently, the most HNT gains are from witnessing other hotspots so the more you can witness the better

**Comment by cokes518** [comment] 2022-04-15 16:11
looks like the issue is resolved by signing out. closing

**Closed by cokes518** 2022-04-15 16:11 UTC

**Comment by unixman427** [comment] 2023-04-28 22:31
I cannot see how to log out of the IOS application. There is no option to do that anywhere. HOW is it done?

**Comment by Ryan-Goldstein** [comment] 2023-04-28 22:50
> I cannot see how to log out of the IOS application. There is no option to do that anywhere. HOW is it done?

Settings gear on the top right of the $ tab > Remove Wallet

**Comment by unixman427** [comment] 2023-04-28 23:02
Thanks. I was able to do that. Now it is a waiting game to see if it shows
the miner rewards now.
