### ISSUE TITLE
Transfer Successful but still no transfer please help

### ISSUE THREAD

**Issue by BarisTonbul** [helium/hotspot-app#1131] opened 2021-11-30 16:08 UTC
Hello i sent transfer hotspot transaction and buyer has accepted but it is still appearing in my wallet. What is the problem ?  How can we solve that bug ? On notifications tab it says completed Successful but still same

My address (Seller) : 14nVXtx1NnkZGxbeUjVCvF9jBmYCuz29QAvTyQxPsGmaBLw68mq
Buyer address : 132pAYnHoW13fx9V9RhMewvVKTkXKr6ZQMw1ciwUrwr3eo8pJUZ
Hotspot address: Wide Bronze Stork 112kcr1HS81qJ6KhzwP2D4j5ySGRRgqco5DN9EsuJUjVovXSX3sV

please help 
![hotspot](https://user-images.githubusercontent.com/34234945/144083825-be3f1030-b398-46e6-a593-4963ed72cec3.png)

**Comment by cokes518** [comment] 2021-11-30 20:00
Hi, it looks like this was attempted during the API outage. The service has been restored and the pending transaction queue is being processed. You should see it go through and succeed.

**Comment by BarisTonbul** [comment] 2021-11-30 20:11
> 

No its still same, should i sent transaction again and again ?

**Comment by cokes518** [comment] 2021-11-30 20:14
it is still pending. don't do anything.

https://api.helium.io/v1/accounts/14nVXtx1NnkZGxbeUjVCvF9jBmYCuz29QAvTyQxPsGmaBLw68mq/pending_transactions

See that it says "Status: Pending"?

<img width="583" alt="image" src="https://user-images.githubusercontent.com/19331274/144120993-489bbe43-36d6-44d4-ae39-2d772edd9ab3.png">

**Comment by cokes518** [comment] 2021-11-30 22:28
looks like this went through. new owner is `132pAY..`

**Comment by cokes518** [comment] 2021-11-30 22:28
closing as fixed. root cause is API outage and pending transaction queue.

**Closed by cokes518** 2021-11-30 22:28 UTC
Labels: bug

**Comment by BarisTonbul** [comment] 2021-12-01 01:17
Ty !
