### ISSUE TITLE
Restoring 12 words to iPad Air Gen 3 causes empty wallet

### ISSUE THREAD

**Issue by timcooijmans** [helium/hotspot-app#959] opened 2021-09-29 13:38 UTC
**Describe the bug**
Our customer reported an issue that after restoring a 12 word seed to an iPad Air Gen. 3 no hotspots and 0 HNT balance was shown while the account owned hotspots and had balance. 

We could verify that the address/public-key reported by the app was correct (by scanning the QR-code and copying the address). 

Restoring the same 12 word seed to an iPhone XR did allow for the hotspots and HNT balance to be shown.

**Comment by cokes518** [comment] 2021-09-30 16:34
is this reproducible? Wonder if it was an API issue where the balance wasn't reported in time

**Comment by timcooijmans** [comment] 2021-09-30 17:18
Not completely sure; The issue was persistent the whole time (several days) for sure (so not a one time thing). But I don’t think the customer re-installed the app so not sure long time cache or something could explain this. I will ask.

**Comment by timcooijmans** [comment] 2021-09-30 20:19
@cokes518 reproducable:

Re-installing app and restoring 12-word seed on iPad Air shows no balance or hotspots. Address in QR is correct.

Doing the same on iPhone XR does show balance and hotspots.

**Comment by cokes518** [comment] 2021-12-09 16:42
we can't reproduce on our end - closing this issue. please reopen if that customer is still having issues.

**Closed by cokes518** 2021-12-09 16:42 UTC
Labels: bug
