### ISSUE TITLE
Zoom map to neatly encapsulate witnesses, when selected 

### ISSUE THREAD

**Issue by PeterMain** [helium/hotspot-app#315] opened 2021-02-26 13:01 UTC
When viewing witnesses, the map moves into a position to enable the hotspots to be seen, but it seems to move to an arbitrary zoom now, vs trying to fit all witnesses in the middle, say, 80% of the screen.

**Comment by tyler-whitman** [comment] 2021-03-08 18:50
This is a duplicate of #184

**Closed** 2021-03-08 18:50 UTC
Labels: UX Improvement
