### ISSUE TITLE
Independent or logarithmic axis for HNT sent/received bar charts

### ISSUE THREAD

**Issue by davetapley** [helium/hotspot-app#640] opened 2021-06-04 18:04 UTC
I _assume_ most people's hotspot(s) wallets will look like this:
1. Lots of relatively small 'receive' transactions (from rewards), and:
2. Occasional relatively large 'send' transactions (as HNT are sent to exchanges and/or consolidated to another wallet).

In this case I'd expect the bar chart to end up looking a bit awkward, like mine does presently (see screenshot below).

Could we decouple the sent/received axis scales, or if that's difficult perhaps a logarithmic scale would make more sense?
I assume the purpose is to give a general sense of activity, and not be an accurate linear representation?

![Screenshot_20210604-105231_Helium](https://user-images.githubusercontent.com/48232/120844030-afddad80-c523-11eb-8bea-26513a054634.jpeg)

**Comment by davetapley** [comment] 2021-06-04 18:09
Actually, I 👀  the code and I think this is a bug...

For up (received) we have:
https://github.com/helium/hotspot-app/blob/f42f3dc681ed7d98587b7cb472f87ae0951beec4/src/components/BarChart/Chart.tsx#L179-L182

For down (sent) we have:
https://github.com/helium/hotspot-app/blob/f42f3dc681ed7d98587b7cb472f87ae0951beec4/src/components/BarChart/Chart.tsx#L190-L193

Both cases use `maxUpBarHeight`, but we also calculate a (never used) `maxDownBarHeight`:
https://github.com/helium/hotspot-app/blob/f42f3dc681ed7d98587b7cb472f87ae0951beec4/src/components/BarChart/Chart.tsx#L120

**Comment by davetapley** [comment] 2021-06-04 18:10
@allenan looks like this feature came in on 9434e19b10396eb37cc59151497d931df6099a46, does my theory about bug/typo make sense? ⬆️

**Comment by matthewcarlreetz** [comment] 2021-06-09 16:33
> > Actually, I 👀 the code and I think this is a bug...
> > For up (received) we have:
> > https://github.com/helium/hotspot-app/blob/f42f3dc681ed7d98587b7cb472f87ae0951beec4/src/components/BarChart/Chart.tsx#L179-L182
> > 
> > For down (sent) we have:
> > https://github.com/helium/hotspot-app/blob/f42f3dc681ed7d98587b7cb472f87ae0951beec4/src/components/BarChart/Chart.tsx#L190-L193
> > 
> > Both cases use `maxUpBarHeight`, but we also calculate a (never used) `maxDownBarHeight`:
> > https://github.com/helium/hotspot-app/blob/f42f3dc681ed7d98587b7cb472f87ae0951beec4/src/components/BarChart/Chart.tsx#L120
> 
> @matthewcarlreetz can you take a look at this comment to see if it's a bug?

As far as I can tell there is not a bug here. The calculation seems to be linear which would result in the chart looking like the screenshot above.

**Comment by davetapley** [comment] 2021-06-14 17:14
@matthewcarlreetz you are correct in that it's linear, but the presence of an **unused** `maxDownBarHeight` seems to imply that it should have it's own scale (but is erroneously using `maxUpBarHeight` due to typo).

**Comment by cokes518** [comment] 2021-11-16 21:47
thanks for submitting this request. we've since had to remove the charts from the app for performance improvements. closing this as won't-fix.

**Closed by cokes518** 2021-11-16 21:47 UTC
