### ISSUE TITLE
Android: Unable to reimport account

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#247] opened 2021-02-20 16:37 UTC
Reported by BFGNeil (mod) on pixel 4, using the latest Android Beta track:

User tried to reimport an account using seed phrase, app crashed. Has tried to clear cache and local storage, and uninstalled the app. Reinstalling the app, then importing works. But once the app reopens, it crashes.

crash report submitted to play store -

**Comment by cokes518** [comment] 2021-02-20 16:48
reproducible on pixel 3. Import works fine. but once you close the app and reopen, it crashes.

**Comment by BFGNeil** [comment] 2021-02-20 16:48
The app is intermittent in crashing, every 3rd or so try it will open

https://user-images.githubusercontent.com/79230094/108602694-48985500-739b-11eb-8a20-366faa950274.mp4

**Comment by tyler-whitman** [comment] 2021-02-20 19:15
Are you doing anything when you open the app? Or just sitting on the hotspots screen and it crashes?

**Comment by BFGNeil** [comment] 2021-02-20 21:45
> Are you doing anything when you open the app? Or just sitting on the hotspots screen and it crashes?

When minimising the app, and opening it again it crashes, then when clicking on the app again it'll instantly crash, the problem is intermittent but often fixed by clicking force stop when google suggests it keeps closing.

**Closed** 2021-02-21 01:04 UTC
Labels: android, app parity, bug
