### ISSUE TITLE
Unable to transfer hotspot

### ISSUE THREAD

**Issue by b-spillman** [helium/hotspot-app#1021] opened 2021-10-31 19:34 UTC
**Describe the bug**
"Transfer Hotspot" button / selection is not active and unable to click it to open. 

**To Reproduce**

1. Go to settings 
2. Click on transfer hotspot
3. See error

**Expected behavior**
Before the app update you would click on the Transfer Hotspot and the next screen appears to enter the Hotspot name that you are wanting to transfer.

**Screenshots**

![Screenshot_20211031-124548_Helium](https://user-images.githubusercontent.com/54695026/139598581-e7391e22-2306-4abf-b7ea-72acf5508479.jpg)

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy
- OS: Android 
- App Version 3.7.1

**Additional context**

**Comment by cokes518** [comment] 2021-11-01 15:28
what troubleshooting steps have you tried @b-spillman ?

**Comment by cokes518** [comment] 2021-11-02 18:34
duplicate of #1017

**Closed by cokes518** 2021-11-02 18:34 UTC
Labels: bug
