### ISSUE TITLE
Can not send HNT in either Helium or Helium Wallet app to Crypto.com deposit HNT.

### ISSUE THREAD

**Issue by PaulOski2022** [helium/hotspot-app#1351] opened 2022-09-06 13:37 UTC
**Describe the bug**

**To Reproduce**

1. Go to Send HNT
2. Paste  Crypto.com wallet address starts with 0xF8........
3. Enter amount of HNT, i entered less than max to account for HNT fee
4. Send HNT is never enabled.

**Expected behavior**
Send HNT is not greyed out and transaction is sent. 

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Samsung Ultra s22

**Additional context**
App is up to date, removed and reinstalled app. Also tried Helium Wallet app.

**Comment by Ryan-Goldstein** [comment] 2022-09-06 13:42
The crypto.com app defaults to using `Cronos`, which is not a Helium address. You need to switch to a Helium address by tapping `Helium`.

**Comment by PaulOski2022** [comment] 2022-09-06 13:47
Cronos is the only option in the Crypto.com app

**Comment by Ryan-Goldstein** [comment] 2022-09-06 15:00
It appears they have paused HNT support:

> Note: LUNA (Cronos), MIR (Cronos), TRB, HNT and AXS withdrawals are paused.
> Luna (Cronos) and MIR (ERC20/Cronos) deposits are paused.

You'll need to contact them to see when they plan to re-enable it.

**Comment by cokes518** [comment] 2022-09-06 16:04
Thanks for sorting out this issue Ryan. Closing as not a bug.

**Closed by cokes518** 2022-09-06 16:04 UTC
Labels: bug
