### ISSUE TITLE
bypass auto lock feature by setting system time back

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#119] opened 2021-01-27 19:02 UTC
**Description**

The "Require PIN" auto lock feature will lock the app automatically after the user specified duration and prompt the user to unlock using PIN / Touch ID.

Assume the user sets the timeout to "4 hours", so the app will lock automatically after 4 hours of inactivity. When the user reopens the app after 4 hours or later, it prompts to unlock before accessing the app.

But this feature does not work as intended, the app locks automatically after 4 hours ONLY if the device screen was in turned ON state for 4 hours.

If the device screen was NOT in turned ON state for 4 hours when the attacker opens the app, it allows to access the app completely without unlocking (it fails to prompt to unlock).

**Root cause:**

I think the auto lock function works in this way: During app close, it creates a scheduled timer `NSTimer.CreateScheduledTimer` that will execute after the user specified duration (4 hours) to check and lock the app. The problem is, the timer will be paused when device enters the sleep mode.

**Solution**:

When the app enters the background state, save the app closed time. After the app enters the foreground state, compare the current device up time with the app closed time. If the difference is greater than the user specified duration (4 hours), then lock the app.

Code to get elapsed real time (device up time including the sleep time), it will not change when the device clock is changed / get affected by the sleep mode:

```func uptime() -> time_t {
    var boottime: timeval
    let mib = [CTL_KERN, KERN_BOOTTIME]
    var size = MemoryLayout.size(ofValue: boottime)
    var now: time_t
    var uptime: time_t = -1

    time(&now)

    if sysctl(mib, 2, &boottime, &size, nil, 0) != -1 && boottime.tv_sec != 0 {
        uptime = now - boottime.tv_sec
    }

    return uptime
}
```
For React native, just create a simple module using the above code and import it in the react native code.
https://reactnative.dev/docs/native-modules-ios

Third party lib: https://www.npmjs.com/package/react-native-relative-time

**Steps to reproduce**

Open the app and login your account.
Go to More > Security, enable "Enable PIN".
Select "Require PIN" to "After 1 minute" (you can also select any other duration).
Close the app and turn OFF the device screen.
After 1 minute or later, turn ON the device screen.
Now reopen the app (it will not prompt to unlock and you can access the app completely).

**Comment by matthewcarlreetz** [comment] 2021-02-26 16:15
I'm unable to reproduce this. Maybe we've already fixed?

**Comment by cokes518** [comment] 2021-02-26 18:32
I'll reply back to the submitter.

**Comment by tyler-whitman** [comment] 2021-03-01 18:50
So I think this one is older, and it already works as explained in the fix to take the time when you minimize and check it when you launch the app.

I did find the opposite bug though, if you quit the app while its in the background the time gets ignored because we dont cache the last idle time. I can fix this so that even if you quit the app it wont ask for your password before the interval is up.

**Comment by tyler-whitman** [comment] 2021-03-01 18:56
> So I think this one is older, and it already works as explained in the fix to take the time when you minimize and check it when you launch the app.
> 
> I did find the opposite bug though, if you quit the app while its in the background the time gets ignored because we dont cache the last idle time vin storage, only app state. I can fix this so that even if you quit the app it wont ask for your password before the interval is up.

Discussed with @allenan and @matthewcarlreetz and we decided to leave it as is. When you quit the app we will require pin no matter how long its been.

**Comment by tyler-whitman** [comment] 2021-03-01 18:57
Maybe we just close this one then? I didn't see any issues with the pin not being asked for.

**Comment by cokes518** [comment] 2021-03-01 19:09
from the bug reporter:

```Hi @coco-helium, I have tested this issue in the new version 3.0.0, it does not occur. This issue occurs in the version 2.9.1 and earlier.

However in the new version, the security app lock can be bypassed easily by reversing the device time.

Open the app and login your account.
Go to More > Security, enable "Enable PIN".
Select "Require PIN" to "After 1 minute".
Close the app.
After 1 minute or LATER, DON'T reopen the app. Change the device time to 1 or 2 hours backward (or any earlier random time which is before the app closed time).
Now reopen the app.
The Problem is using current device time for time interval calculation.

 const now = Date.now()
https://github.com/helium/hotspot-app/blob/9ccd4f15270bffa382c1d839690d9034a18535c2/src/App.tsx#L83

The fix I specified in the initial report elapsed real time will resolve this issue.

Thanks.```

**Comment by cokes518** [comment] 2021-03-02 21:48
Can confirm that this is reproducible. 

Steps to reproduce:
1. Open the app and login your account.
2. Go to More > Security, enable "Enable PIN".
3. Select "Require PIN" to "After 1 minute".
4. Close the app.
5. After 1 minute or LATER, DON'T reopen the app. Change the device time to 1 or 2 hours backward (or any earlier random time which is before the app closed time).
6. Now reopen the app.
The Problem is using current device time for time interval calculation.

`const now = Date.now()`
https://github.com/helium/hotspot-app/blob/9ccd4f15270bffa382c1d839690d9034a18535c2/src/App.tsx#L83

The fix I specified in the initial report elapsed real time will resolve this issue.

**Closed** 2021-07-26 18:04 UTC
Labels: bug
