### ISSUE TITLE
Hellium Hotspot App Issues

### ISSUE THREAD

**Issue by toddeide** [helium/hotspot-app#1107] opened 2021-11-22 18:38 UTC
I have connected my hotspot to my wallet and it says I own the hotspot but it does not show up in the app so i can place the miner in the home.

**Comment by cokes518** [comment] 2021-11-29 17:52
is still this a problem?

**Comment by cokes518** [comment] 2021-11-30 21:42
this looks to be a duplicate of #1108

**Closed by cokes518** 2021-11-30 21:42 UTC
Labels: bug

**Comment by JonasHartig** [comment] 2023-05-16 15:54
hi, i know this is a realy old thread but yeah.  At least for me.

**Comment by cokes518** [comment] 2023-05-16 16:41
it's a different root cause.. but it will be fixed in the next app release. keep an eye out for 5.0.4.

**Comment by JonasHartig** [comment] 2023-05-16 17:04
wow that was fast! massive thanks i will wait :)
