### ISSUE TITLE
Onboarding multiple hotspots at once causes issues

### ISSUE THREAD

**Issue by shawaj** [helium/hotspot-app#636] opened 2021-06-03 19:32 UTC
From @ap#7446 on discord...

When onboarding several hotspots one thing I have noticed in app is that when multiple hotspots have their Bluetooth going the onboarding process can pick up another hotspot instead of the selected one. Also only 1 hotspot shows. 

Just to add .. it can show the correct MAC address when searching for the hotspot but when you go through the onboarding it can say that it’s already onboarded as the nearby hotspot must have been picked up. Happened a couple of times until I noticed when the other HS were not offering Bluetooth it was no longer an issue.

**Comment by cokes518** [comment] 2021-06-08 23:59
LOE to fix the issue is higher than asking the user to change behavior and *not* onboard multiple hotspots at once. going to have to close this as won't fix. sorry!

**Closed by cokes518** 2021-06-08 23:59 UTC
Labels: wontfix
